### ISSUE TITLE
[cloudfront-distribution] Should support creating a Route53 record with distribution

### ISSUE THREAD

**Issue by JonRoma** [techservicesillinois/terraform-aws-cloudfront-distribution#4]
The cloudfront-distribution module does not support creating a Route 53 record at the time a distribution is configured. In the past, we created these by hand in the campus DNS in the `techservices.illinois.edu` zone.

Now that we've got a delegated zone `as-test.techservices.illinois.edu` in Route53, we should consider automating the creation of Route53 records for CloudFront distributions. The resulting records would normally reside in  `as-test.techservices.illinois.edu` or some other Amazon-hosted zone.

This begs a couple of questions:

* Should this support be added to the cloudfront-distribution module, or would it be desirable for the DNS record's lifecycle to differ from that of the distribution?

Assuming the latter case, should we create a trivial module to create a DNS record, or should we simply use the stock Terraform `route53_record` resource?

* Should these be CNAME records as in the past, or is there benefit to using Amazon's ALIAS records? Not sure if the latter makes sense or will work, but this is a good time to examine our options.

**Comment by ddriddle** [comment]
@JonRoma I definitely think the `cloudfront-distribution`module should have an optional alias map for defining alias records. At this time I can not think of a use case for having a separate alias module for CloudFront but such cases may exist. At any rate, I'm sure for us they will have the same lifecycle and so should be in a single module.

I do not think a separate submodule would be useful since it would warp only a single Terraform object. I see no value in that.

**Comment by ddriddle** [comment]
FYI this is closely related to: https://github.com/techservicesillinois/terraform-aws-alias/issues/1
